[package]
name = "bb8"
version = "0.4.1"
authors = ["Kyle Huey <khuey@kylehuey.com>", "Dirkjan Ochtman <dirkjan@ochtman.nl>"]
description = "r2d2, but for async tokio based connections"
license = "MIT"
repository = "https://github.com/khuey/bb8"
edition = "2018"
workspace = ".."

[dependencies]
async-trait = "0.1"
futures = "0.3"
tokio = { version = "0.2", features = ["rt-core", "time"] }

[dev-dependencies]
tokio = { version = "0.2", features = ["macros"] }
