[package]
name = "bb8"
version = "0.4.2"
authors = ["Kyle Huey <khuey@kylehuey.com>", "Dirkjan Ochtman <dirkjan@ochtman.nl>"]
description = "Full-featured async (tokio) connection pooling, based on r2d2"
license = "MIT"
repository = "https://github.com/djc/bb8"
edition = "2018"
workspace = ".."

[dependencies]
async-trait = "0.1"
futures-channel = "0.3.2"
futures-util = { version = "0.3.2", default-features = false, features = ["channel"] }
parking_lot = "0.11"
tokio = { version = "0.2", features = ["rt-core", "time"] }

[dev-dependencies]
tokio = { version = "0.2", features = ["macros"] }
