[package]
name = "bb8-postgres"
version = "0.2.0"
authors = ["Kyle Huey <khuey@kylehuey.com>"]

[features]
"with-bit-vec-0.5" = ["tokio-postgres/with-bit-vec-0.5"]
"with-chrono-0.4" = ["tokio-postgres/with-chrono-0.4"]
"with-eui48-0.4" = ["tokio-postgres/with-eui48-0.4"]
"with-geo-0.10" = ["tokio-postgres/with-geo-0.10"]
"with-serde_json-1" = ["tokio-postgres/with-serde_json-1"]
"with-uuid-0.7" = ["tokio-postgres/with-uuid-0.7"]

[dependencies]
bb8 = { path = ".." }
futures = "0.1"
tokio = "0.1"
tokio-postgres = { git = "https://github.com/khuey/rust-postgres", branch = "puberror" }

[dev-dependencies]
futures-state-stream = "0.2"
