[package]
name = "bb8-postgres"
version = "0.2.0"
authors = ["Kyle Huey <khuey@kylehuey.com>"]

[features]
"with-bit-vec-0_5" = ["tokio-postgres/with-bit-vec-0_5"]
"with-chrono-0_4" = ["tokio-postgres/with-chrono-0_4"]
"with-eui48-0_4" = ["tokio-postgres/with-eui48-0_4"]
"with-geo-types-0_4" = ["tokio-postgres/with-geo-types-0_4"]
"with-serde_json-1" = ["tokio-postgres/with-serde_json-1"]
"with-uuid-0_7" = ["tokio-postgres/with-uuid-0_7"]

[dependencies]
bb8 = { path = ".." }
futures = "0.1"
tokio = "0.1"
tokio-postgres = "0.4.0-rc.2"

[dev-dependencies]
futures-state-stream = "0.2"
